"use client";
import { useState } from "react";
import { CheckCircle2, Command, MoreHorizontal, Power, RefreshCw, Search, SlidersHorizontal, Wifi, Wrench } from "lucide-react";

const initial = [
  { name: "4th & Main — Midtown", location: "Portland, OR", status: "Live", uptime: "99.98%", now: "Grand opening · Juniper Lane", temp: "42°C", signal: "Excellent" },
  { name: "Hawthorne & 12th", location: "Portland, OR", status: "Live", uptime: "99.92%", now: "Night market weekend", temp: "39°C", signal: "Excellent" },
  { name: "Union Station Atrium", location: "Sacramento, CA", status: "Offline", uptime: "96.20%", now: "No creative playing", temp: "—", signal: "No signal" },
];

export default function ScreenManager() {
  const [screens, setScreens] = useState(initial);
  const [notice, setNotice] = useState("");
  const runCommand = (name: string, command: string) => { setNotice(`${command} sent to ${name}.`); setTimeout(() => setNotice(""), 2600); };
  return <div className="mx-auto max-w-7xl space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-cyan-300">Operations</p><h2 className="mt-2 text-3xl font-bold">Screen manager</h2><p className="mt-2 text-sm text-white/50">Control every player, schedule, and health signal from one place.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-300 to-blue-400 px-4 py-2.5 text-sm font-semibold text-[#04121a]"><Wrench className="h-4 w-4"/>Run network check</button></div>
    {notice && <div className="rounded-xl border border-cyan-300/20 bg-cyan-300/10 px-4 py-3 text-sm text-cyan-100">✓ {notice}</div>}
    <div className="flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2.5"><Search className="h-4 w-4 text-white/35"/><input className="!border-0 !bg-transparent !p-0 text-sm" placeholder="Search by name or location..."/></div><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm text-white/60"><SlidersHorizontal className="h-4 w-4"/>Filters</button></div>
    <div className="space-y-4">{screens.map(screen => <section key={screen.name} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex items-start gap-3"><div className={`grid h-11 w-11 place-items-center rounded-xl ${screen.status === "Live" ? "bg-emerald-400/10 text-emerald-200" : "bg-amber-400/10 text-amber-200"}`}><MonitorIcon/></div><div><h3 className="font-semibold">{screen.name}</h3><p className="mt-1 text-xs text-white/40">{screen.location} · Player ADB-29{screen.status === "Offline" ? " · Last seen 18m ago" : ""}</p></div></div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] ${screen.status === "Live" ? "bg-emerald-400/10 text-emerald-200" : "bg-amber-400/10 text-amber-200"}`}>{screen.status}</span><button className="text-white/35"><MoreHorizontal className="h-5 w-5"/></button></div></div><div className="mt-5 grid gap-4 border-t border-white/10 pt-4 sm:grid-cols-4"><div><p className="text-[10px] uppercase tracking-widest text-white/35">Now playing</p><p className="mt-2 truncate text-sm text-white/75">{screen.now}</p></div><div><p className="text-[10px] uppercase tracking-widest text-white/35">Uptime</p><p className="mt-2 text-sm">{screen.uptime}</p></div><div><p className="text-[10px] uppercase tracking-widest text-white/35">Temperature</p><p className="mt-2 text-sm">{screen.temp}</p></div><div><p className="text-[10px] uppercase tracking-widest text-white/35">Signal</p><p className="mt-2 flex items-center gap-1.5 text-sm"><Wifi className={`h-3.5 w-3.5 ${screen.signal === "Excellent" ? "text-emerald-300" : "text-amber-300"}`}/>{screen.signal}</p></div></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>runCommand(screen.name,"Refresh command")} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-white/65"><RefreshCw className="h-3.5 w-3.5"/>Refresh player</button><button onClick={()=>runCommand(screen.name,"Preview command")} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs text-white/65"><Command className="h-3.5 w-3.5"/>Preview screen</button><button onClick={()=>runCommand(screen.name,"Power cycle command")} className="inline-flex items-center gap-2 rounded-lg border border-rose-300/20 px-3 py-2 text-xs text-rose-200"><Power className="h-3.5 w-3.5"/>Power cycle</button></div></section>)}</div>
  </div>;
}
function MonitorIcon(){return <CheckCircle2 className="h-5 w-5"/>}
