"use client";

import Link from "next/link";
import { ArrowUpRight, MoreHorizontal, Plus, TrendingUp } from "lucide-react";

const screens = [{ name: "4th & Main — Midtown", city: "Portland, OR", fill: "84%", revenue: "$2,480.00", status: "Live" }, { name: "Hawthorne & 12th", city: "Portland, OR", fill: "67%", revenue: "$1,340.50", status: "Live" }, { name: "Union Station Atrium", city: "Sacramento, CA", fill: "42%", revenue: "$620.00", status: "Needs attention" }];

export default function PortalOverview() {
  return <div className="mx-auto max-w-7xl space-y-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-cyan-300">Friday, October 2, 2026</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Your network at a glance</h2><p className="mt-2 text-sm text-white/50">Keep your screens full, healthy, and earning.</p></div><Link href="/portal/screens" className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-300 to-blue-400 px-4 py-2.5 text-sm font-semibold text-[#04121a]"><Plus className="h-4 w-4" />Add a screen</Link></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["$4,440.50", "This month’s revenue", "+18.4%", "text-emerald-300"], ["72%", "Network fill rate", "+6.2%", "text-cyan-300"], ["3", "Active screens", "1 pending review", "text-violet-300"], ["14,280", "Impressions today", "+2,140", "text-amber-300"]].map(([value, label, delta, color]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="flex items-start justify-between"><p className="text-xs text-white/45">{label}</p><TrendingUp className={`h-4 w-4 ${color}`} /></div><p className="mt-4 text-2xl font-bold">{value}</p><p className={`mt-1 text-xs ${color}`}>{delta}</p></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_0.6fr]"><section className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Revenue performance</h3><p className="mt-1 text-xs text-white/40">Last 30 days · all screens</p></div><button className="rounded-lg border border-white/10 px-3 py-1.5 text-xs text-white/55">Last 30 days</button></div><div className="mt-8 flex h-48 items-end gap-2">{[34,42,38,58,52,64,61,78,68,74,84,81,92,88,100,93,98,86,92,100,94,100,97,100,100,100,96,100,100,100].map((h, i) => <div key={i} className="group relative flex-1 rounded-t bg-gradient-to-t from-blue-500/30 to-cyan-300" style={{ height: `${h}%` }}><span className="absolute -top-7 left-1/2 hidden -translate-x-1/2 rounded bg-black px-1.5 py-1 text-[9px] group-hover:block">${Math.round(h * 43)}</span></div>)}</div><div className="mt-3 flex justify-between text-[10px] text-white/30"><span>Sep 3</span><span>Sep 17</span><span>Oct 2</span></div></section><section className="rounded-2xl border border-white/10 bg-gradient-to-br from-violet-500/15 to-cyan-400/10 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-cyan-200/70">Beacon insight</p><h3 className="mt-4 text-xl font-bold">Fill your quiet hours.</h3><p className="mt-3 text-sm leading-relaxed text-white/55">Union Station has 58% open inventory between 10am–2pm. A weekday bundle could add an estimated <span className="font-semibold text-white">$780/mo</span>.</p><Link href="/portal/campaigns" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-cyan-200">Create a bundle <ArrowUpRight className="h-4 w-4" /></Link></section></div>
    <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Your screens</h3><p className="mt-1 text-xs text-white/40">Health, fill, and revenue at a glance</p></div><Link href="/portal/screens" className="text-xs text-cyan-200">Manage screens →</Link></div><div className="mt-5 divide-y divide-white/10">{screens.map(s => <div key={s.name} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-gradient-to-br from-cyan-300/20 to-blue-500/20 text-cyan-200">▦</div><div><p className="text-sm font-medium">{s.name}</p><p className="text-xs text-white/40">{s.city}</p></div></div><div className="flex items-center gap-8 text-right text-xs"><div><p className="text-white/40">Fill rate</p><p className="mt-1 font-semibold">{s.fill}</p></div><div><p className="text-white/40">Revenue</p><p className="mt-1 font-semibold">{s.revenue}</p></div><span className={`rounded-full px-2 py-1 ${s.status === "Live" ? "bg-emerald-400/10 text-emerald-200" : "bg-amber-400/10 text-amber-200"}`}>{s.status}</span><MoreHorizontal className="h-4 w-4 text-white/35" /></div></div>)}</div></section>
  </div>;
}
