"use client";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";

const stats = [["$38,420", "Gross volume", "+22.6%"], ["1,240", "Screens live", "+38 this month"], ["8,492", "Active advertisers", "+14.2%"], ["17", "Needs review", "Across 6 queues"]];

export default function Admin() {
  return <div className="mx-auto max-w-7xl space-y-8"><div><p className="text-sm text-rose-200">Admin command center</p><h2 className="mt-2 text-3xl font-bold">Everything in one view.</h2><p className="mt-2 text-sm text-white/50">Monitor the marketplace, approve demand, and keep the network healthy.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([value, label, delta]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-xs text-white/45">{label}</p><p className="mt-4 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-emerald-200">{delta}</p></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_0.6fr]"><section className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Platform volume</h3><p className="mt-1 text-xs text-white/40">Gross booking value · last 30 days</p></div><Link href="/admin/settings" className="text-xs text-rose-200">Export data →</Link></div><div className="mt-8 flex h-48 items-end gap-2">{[30,42,34,50,48,61,57,70,68,76,73,82,79,88,86,95,91,100,96,100,92,100,98,100,100,96,100,100,100,100].map((height, index) => <div key={index} className="flex-1 rounded-t bg-gradient-to-t from-rose-500/30 to-violet-300" style={{height: `${height}%`}} />)}</div></section><section className="rounded-2xl border border-rose-300/15 bg-rose-300/5 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-rose-200/70">Needs attention</p><div className="mt-5 space-y-4"><div><p className="text-sm font-semibold">12 creatives awaiting review</p><p className="mt-1 text-xs text-white/45">Oldest queued 18 minutes ago</p><Link href="/admin/moderation" className="mt-2 inline-flex items-center gap-1 text-xs text-rose-200">Open queue <ArrowUpRight className="h-3 w-3" /></Link></div><div className="border-t border-white/10 pt-4"><p className="text-sm font-semibold">3 screens offline</p><p className="mt-1 text-xs text-white/45">Potential lost revenue: $420/day</p></div></div></section></div>
    <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><h3 className="font-semibold">Recent platform activity</h3><div className="mt-5 divide-y divide-white/10">{["New owner approved · Rivera Outdoor Media", "Campaign flagged for manual review · #AD-8831", "Payout batch completed · $28,440.20", "Screen network health check completed · 99.98% uptime"].map((activity, index) => <div key={activity} className="flex items-center justify-between py-4 text-sm"><span>{activity}</span><span className="text-xs text-white/35">{index + 2}m ago</span></div>)}</div></section></div>;
}
